### ISSUE TITLE
Open panel kicks off a directory listing when being cancelled

### ISSUE THREAD

**Issue by mikeabdullah** [karelia/ConnectionKit#77]
I go through steps along these lines:
1. Show the a connection open panel. This goes fine, directory listing comes up etc.
2. Click the Cancel button.

This is where things are a bit odd. As you can see from the stack trace below, the act of cancelling the panel attempts to kick off a directory listing.

```
#0  0x00000001009205c7 in -[CK2OpenPanelController childrenForURL:] at /Users/Mike/Code/Karelia/Sandvox/Code/ConnectionKit/ConnectionKit/CK2OpenPanelController.m:637
#1  0x0000000100927f31 in -[CK2OpenPanelColumnViewController browser:numberOfChildrenOfItem:] at /Users/Mike/Code/Karelia/Sandvox/Code/ConnectionKit/ConnectionKit/CK2OpenPanelColumnViewController.m:368
#2  0x00007fff90c9aecc in -[NSTableView _uncachedNumberOfRows] ()
#3  0x00007fff90c9add3 in -[_NSTableRowHeightStorage numberOfRows] ()
#4  0x00007fff90ca1a45 in -[NSTableView _verifySelectionIsOK] ()
#5  0x00007fff90ca143e in -[NSTableView _tileAndRedisplayAll] ()
#6  0x00007fff90f1d5ad in -[_NSBrowserTableColumnViewController setView:] ()
#7  0x00007fff90f1e203 in -[NSBrowserColumnViewController setColumnView:forcingFlippedBehavior:] ()
#8  0x00007fff90f1dbca in -[_NSBrowserTableColumnViewController loadView] ()
#9  0x00007fff9102dcf7 in -[NSViewController _loadViewIfRequired] ()
#10 0x00007fff90cfef91 in -[NSViewController view] ()
#11 0x00007fff90f1d887 in -[NSBrowserColumnViewController setMenu:] ()
#12 0x00007fff90f1cf64 in -[NSBrowser addColumn] ()
#13 0x00007fff90f1c7b4 in -[NSBrowser loadColumnZero] ()
#14 0x0000000100927416 in -[CK2OpenPanelColumnViewController reload] at /Users/Mike/Code/Karelia/Sandvox/Code/ConnectionKit/ConnectionKit/CK2OpenPanelColumnViewController.m:211
#15 0x000000010091f6bf in -[CK2OpenPanelController resetSession] at /Users/Mike/Code/Karelia/Sandvox/Code/ConnectionKit/ConnectionKit/CK2OpenPanelController.m:432
#16 0x000000010091b565 in -[CK2OpenPanel endWithCode:] at /Users/Mike/Code/Karelia/Sandvox/Code/ConnectionKit/ConnectionKit/CK2OpenPanel.m:221
#17 0x000000010091b9c4 in -[CK2OpenPanel cancel:] at /Users/Mike/Code/Karelia/Sandvox/Code/ConnectionKit/ConnectionKit/CK2OpenPanel.m:266
#18 0x0000000100922066 in -[CK2OpenPanelController cancel:] at /Users/Mike/Code/Karelia/Sandvox/Code/ConnectionKit/ConnectionKit/CK2OpenPanelController.m:911
#19 0x00007fff8a062cd7 in _os_activity_initiate ()
#20 0x00007fff90e0f6d7 in -[NSApplication sendAction:to:from:] ()
```

This becomes somewhat of a nuisance because the directory listing needs authentication for something like FTP. The panel controller gets asked to authenticate; it sees it has no delegate any more, so asks the file manager to perform its default handling. The default handling is to have a go with whatever username and password are present in the URL, so in all likelihood fails (because there's no password there).

The end result is every time I close the open panel, one failed FTP logic attempt results. Given a little time, this could easily get the user blacklisted on some servers.

This used to much more of a problem before commit c8bd2cdcb291b79068321a174009c982165b2102 as the default handling would go round in circles retrying auth forever more.

**Comment by MrNoodle** [comment]
I can remove the view reloads (which re-fetches the data). It seems to work fine without them as long as you set the URL/directory next time you use it (which will reload the views), which I think is the normal usage pattern. Should I also reset the directory URL to nil?

**Comment by mikeabdullah** [comment]
I think it seems reasonable to me to keep the directory URL the same as it was before.

I have to admit in our code we're creating a fresh open panel each time, so I haven't looked that much at how that might affect panel re-use.

**Comment by MrNoodle** [comment]
Just pushed the fix. Confirm it on your end and close if it works for you.

**Comment by mikeabdullah** [comment]
I fear there's more to it than that. If I:
1. Bring up the panel
2. Navigate to a folder
3. Click OK

I now get this:

```
#0  0x00007fff906486b3 in objc_exception_throw ()
#1  0x00007fff8dfc174e in -[__NSArrayI objectAtIndex:] ()
#2  0x0000000100927e59 in -[CK2OpenPanelColumnViewController browser:child:ofItem:] at /Users/Mike/Code/Karelia/Sandvox/Code/ConnectionKit/ConnectionKit/CK2OpenPanelColumnViewController.m:358
#3  0x000000010092797b in __48-[CK2OpenPanelColumnViewController selectedURLs]_block_invoke at /Users/Mike/Code/Karelia/Sandvox/Code/ConnectionKit/ConnectionKit/CK2OpenPanelColumnViewController.m:300
#4  0x00007fff918bbdec in __NSIndexSetEnumerate ()
#5  0x0000000100927913 in -[CK2OpenPanelColumnViewController selectedURLs] at /Users/Mike/Code/Karelia/Sandvox/Code/ConnectionKit/ConnectionKit/CK2OpenPanelColumnViewController.m:295
#6  0x00000001009211d1 in -[CK2OpenPanelController validateProgressIndicator] at /Users/Mike/Code/Karelia/Sandvox/Code/ConnectionKit/ConnectionKit/CK2OpenPanelController.m:800
#7  0x000000010092062a in -[CK2OpenPanelController childrenForURL:] at /Users/Mike/Code/Karelia/Sandvox/Code/ConnectionKit/ConnectionKit/CK2OpenPanelController.m:671
#8  0x0000000100927e05 in -[CK2OpenPanelColumnViewController browser:child:ofItem:] at /Users/Mike/Code/Karelia/Sandvox/Code/ConnectionKit/ConnectionKit/CK2OpenPanelColumnViewController.m:352
#9  0x000000010092797b in __48-[CK2OpenPanelColumnViewController selectedURLs]_block_invoke at /Users/Mike/Code/Karelia/Sandvox/Code/ConnectionKit/ConnectionKit/CK2OpenPanelColumnViewController.m:300
#10 0x00007fff918bbdec in __NSIndexSetEnumerate ()
#11 0x0000000100927913 in -[CK2OpenPanelColumnViewController selectedURLs] at /Users/Mike/Code/Karelia/Sandvox/Code/ConnectionKit/ConnectionKit/CK2OpenPanelColumnViewController.m:295
#12 0x00000001009211d1 in -[CK2OpenPanelController validateProgressIndicator] at /Users/Mike/Code/Karelia/Sandvox/Code/ConnectionKit/ConnectionKit/CK2OpenPanelController.m:800
#13 0x00000001009210c7 in -[CK2OpenPanelController validateViews] at /Users/Mike/Code/Karelia/Sandvox/Code/ConnectionKit/ConnectionKit/CK2OpenPanelController.m:779
#14 0x000000010091f654 in -[CK2OpenPanelController resetSession] at /Users/Mike/Code/Karelia/Sandvox/Code/ConnectionKit/ConnectionKit/CK2OpenPanelController.m:431
#15 0x000000010091b505 in -[CK2OpenPanel endWithCode:] at /Users/Mike/Code/Karelia/Sandvox/Code/ConnectionKit/ConnectionKit/CK2OpenPanel.m:223
#16 0x000000010091b902 in -[CK2OpenPanel ok:] at /Users/Mike/Code/Karelia/Sandvox/Code/ConnectionKit/ConnectionKit/CK2OpenPanel.m:263
#17 0x0000000100921fd9 in -[CK2OpenPanelController ok:] at /Users/Mike/Code/Karelia/Sandvox/Code/ConnectionKit/ConnectionKit/CK2OpenPanelController.m:907
#18 0x00007fff8a062cd7 in _os_activity_initiate ()
#19 0x00007fff90e0f6d7 in -[NSApplication sendAction:to:from:] ()
```

I've selected item 17 of a particular folder. That's what the browser's data source is being asked for. But at this point in time, it looks the panel has been reset in some fashion, because all that's present in the data source is:

```
Printing description of children:
(
    "Loading%E2%80%A6"
)
```

**Comment by MrNoodle** [comment]
Ack, you're right. Will take a closer look at it. It probably doesn't need to do anything with the UI really so I'll also defer validating.

**Comment by mikeabdullah** [comment]
Excellent, working a treat for me!
